spring.application.name=api
# --- CONEXIÓN A BASE DE DATOS ---
spring.datasource.url=jdbc:mysql://localhost:3306/ecohospedajes_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=9630Jean993

# --- CONFIGURACIÓN JPA / HIBERNATE ---
# Esto crea las tablas automáticamente cuando inicias el proyecto
spring.jpa.hibernate.ddl-auto=update
# Esto nos permite ver en la consola el SQL que Java escribe por nosotros (útil para debug)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# --- CONFIGURACIÓN DE ERRORES (Para ver mensajes claros en el Frontend) ---
server.error.include-message=always
server.error.include-binding-errors=always